name: Send Telegram Notification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Send Message in Telegram
    runs-on: ubuntu-latest
    steps:
    - name: Send Message in Telegram
      uses: appleboy/telegram-action@master
      with:
        to: -1001488016153
        token: 1292775840:AAE4dwneT6Nr6x4C-07feYgFiMjpms18DFU
        message: |
          Project: GitDemo
          Commit Message: ${{ github.event.head_commit.message }}
          Commited Actor: ${{ github.actor }}
